groups:
- name: DHCP
  rules:
  - alert: DHCPServerOffline
    expr: node_systemd_unit_state{name="dhcpd.service", state="active"} < 1
    for: 5m
    labels:
      severity: page
    annotations:
      description: 'Host {{ $labels.instance }} is reporting that the expected DHCP service is not running.'
      summary: 'Host {{ $labels.instance }} DHCP offline'
