groups:
- name: HAProxy
  rules:
  - alert: HAProxyOffline
    expr: node_systemd_unit_state{name="haproxy.service", state="active"} < 1
    for: 5m
    labels:
      severity: page
    annotations:
      description: 'Host {{ $labels.instance }} is reporting that the expected HAProxy service is not running.'
      summary: 'Host {{ $labels.instance }} HAProxy offline'
