groups:
- name: IdM
  rules:
  - alert: KerberosKDCServiceOffline
    expr: node_systemd_unit_state{name="krb5kdc.service", state="active"} < 1
    for: 5m
    labels:
      severity: page
    annotations:
      description: 'Host {{ $labels.instance }} is reporting that the expected Kerberos KDC service is not running.'
      summary: 'Host {{ $labels.instance }} Kerberos KDC offline'
  - alert: DirectoryServiceOffline
    expr: node_systemd_unit_state{name=~"dirsrv.*\.service", state="active"} < 1
    for: 5m
    labels:
      severity: page
    annotations:
      description: 'Host {{ $labels.instance }} is reporting that the expected directory service is not running.'
      summary: 'Host {{ $labels.instance }} directory service offline'
  - alert: KAdminServiceOffline
    expr: node_systemd_unit_state{name="kadmin.service", state="active"} < 1
    for: 5m
    labels:
      severity: page
    annotations:
      description: 'Host {{ $labels.instance }} is reporting that the expected kadmin service is not running.'
      summary: 'Host {{ $labels.instance }} kadmin service offline'
  - alert: HTTPDServiceOffline
    expr: node_systemd_unit_state{name="httpd.service", state="active"} < 1
    for: 5m
    labels:
      severity: page
    annotations:
      description: 'Host {{ $labels.instance }} is reporting that the expected httpd service is not running.'
      summary: 'Host {{ $labels.instance }} httpd service offline'
  - alert: PKITomcatDServiceOffline
    expr: node_systemd_unit_state{name="pki-tomcatd.target", state="active"} < 1
    for: 5m
    labels:
      severity: page
    annotations:
      description: 'Host {{ $labels.instance }} is reporting that the expected Tomcat service is not running.'
      summary: 'Host {{ $labels.instance }} Tomcat service offline'
  - alert: IPAServiceOffline
    expr: node_systemd_unit_state{name=~"ipa.service", state="active"} < 1
    for: 5m
    labels:
      severity: page
    annotations:
      description: 'Host {{ $labels.instance }} is reporting that the expected IPA service is not running.'
      summary: 'Host {{ $labels.instance }} IPA service offline'