---
- name: Install Docker
  hosts: prometheus_target:prometheus_target_bind:prometheus_target_haproxy
  become: True
  roles:
    - infra-ansible/roles/config-docker
  tags:
    - 'never'
    - 'install'

- name: Setup node exporters
  hosts: prometheus_target
  become: True
  vars:
    provision_state: "started"
  roles:
    - ../../../prometheus/generic/setup-node-exporter
  tags:
    - 'always'

- name: Setup bind exporters
  hosts: prometheus_target_bind
  become: True
  vars:
    provision_state: "started"
  roles:
    - ../../../prometheus/generic/setup-bind-exporter
  tags:
    - 'always'

- name: Setup haproxy exporters
  hosts: prometheus_target_haproxy
  become: True
  vars:
    provision_state: "started"
  roles:
    - ../../../prometheus/generic/setup-haproxy-exporter
  tags:
    - 'always'
