---
- name: Install Docker
  hosts: prometheus_target
  become: True
  roles:
    - infra-ansible/roles/config-docker
  tags:
    - 'never'
    - 'install'

- name: Setup node exporters
  hosts: prometheus_target
  become: True
  vars:
    provision_state: "started"
  roles:
    - ../../../prometheus/generic/setup-node-exporter
  tags:
    - 'always'
