---
aws_cfs_exporter_image: 'prom/aws-cloudformation-stacks-exporter'
aws_cfs_exporter_image_version: 'latest'
aws_cfs_exporter_port: '8080'

provision_state: "started"

ansible_cfs_exporter:
   - awsAccount: "Dummy-Account"
     port: 9420
     apikey: 22222
     secretkey: 3333
     regions: "us-east-1"
