# This is the Ansible Galaxy requirements file to pull in the correct roles
# to support the operation of this Ansible approach.

- name: openshift-applier
  scm: git
  src: https://github.com/redhat-cop/openshift-applier.git
  version: v2.0.0
