---
# smtp config for alertmanager
smtp_host: my_smtp_host
smtp_port: my_smtp_port
from: my_smtp_from
smtp_username: 'smtp_user'
smtp_password: 'smtp_password'
smtp_tls: 'false'
notification_recipients: somebody@example.com


# directory from which grafana dashboards are copied
dashboard_dir: /home/user/dashbooards

#custom rules file
custom_rules_file: /path/to/custom/rules_file.yml
