---
- name: Install Docker
  hosts: prometheus
  become: True
  roles:
    - infra-ansible/roles/config-docker

- name: Setup node exporters
  hosts: prometheus_target
  become: True
  vars:
    provision_state: "absent"
  roles:
    - ../../../prometheus/generic/setup-node-exporter

- name: Setup prometheus
  hosts: monitoring-hosts
  become: True
  vars:
    provision_state: "absent"
  roles:
    - ../../../prometheus/generic/setup-prometheus
    - ../../../grafana/generic/setup-grafana
