---
# tasks file for add-ssl-target

- name: create targets directory
  file:
    path: /home/centos/targets/ssl_targets
    state: directory
    mode: '0755'
    owner: centos
    group: centos
    seuser: system_u
    setype: container_file_t

- name: template the targets
  template:
    src: ssl_target.yml.j2
    dest: /home/centos/targets/ssl_targets/ssl_target_{{ item }}.yml
    mode: '0755'
    owner: centos
    group: centos
    seuser: system_u
    setype: container_file_t
  loop: "{{ ssl_certs }}"
