---
- name: Run the alertmanager.yml template
  template:
    src: alertmanager.yml.j2
    dest: "/home/{{ ansible_user }}/alertmanager.yml"
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run Alertmanager Docker container
  docker_container:
    name: alertmanager
    image: "{{ alertmanager_image }}:{{ alertmanager_image_version }}"
    restart_policy: unless-stopped
    published_ports:
    - "{{ alertmanager_port }}:9093"
    volumes:
    - "/home/{{ ansible_user }}/alertmanager.yml:/etc/alertmanager/alertmanager.yml:Z"
    state: "{{ provision_state }}"
    recreate: yes
