---

- name: Ensure that the monitoring config directory exists
  file:
    path: /opt/monitoring
    state: directory

- name: Run the alertmanager.yml template
  template:
    src: alertmanager.yml.j2
    dest: "/opt/monitoring/alertmanager.yml"
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Enable firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Open Firewall for DNS
  firewalld:
    port: "{{item}}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - 9093/tcp

- name: Run Alertmanager Docker container
  docker_container:
    name: alertmanager
    image: "{{ alertmanager_image }}:{{ alertmanager_image_version }}"
    restart_policy: unless-stopped
    published_ports:
    - "{{ alertmanager_port }}:9093"
    volumes:
    - "/opt/monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:Z"
    state: "{{ provision_state }}"
    recreate: yes
