---
- name: Install Docker
  hosts: prometheus
  become: True
  roles:
    - infra-ansible/roles/config-docker
  tags:
    - 'never'
    - 'install'

- name: Setup node exporters
  hosts: prometheus_target
  become: True
  vars:
    provision_state: "started"
  roles:
    - ../../prometheus/generic/setup-node-exporter
  tags:
    - 'always'


- name: Setup prometheus and alertmanager
  hosts: prometheus_scraper
  become: True
  vars:
    provision_state: "started"
  roles:
    - ../../prometheus/generic/setup-prometheus
    - ../../grafana/generic/setup-grafana
    - ../../prometheus/generic/setup-alertmanager
  tags:
    - 'always'
