---
- name: Install Docker
  hosts: prometheus
  become: True
  roles:
    - infra-ansible/roles/config-docker
  tags:
    - 'never'
    - 'install'

- name: Setup bind exporters
  hosts: prometheus_target_bind
  become: True
  vars:
    provision_state: "started"
  roles:
    - ../../prometheus/generic/setup-bind-exporter
  tags:
    - 'always'
