---
ssl_expiration_warning_threshold: '7'
ssl_expiration_critical_threshold: '3'

memory_usage_warning_threshold: '70'
memory_usage_critical_threshold: '90'

disk_usage_warning_threshold: '70'
disk_usage_critical_threshold: '90'

config_dir: "/opt/monitoring"
