---
kind: Template
apiVersion: v1
labels:
  template: secret-template
metadata:
  annotations:
    description: |-
      Secret template.
  name: secret
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    creationTimestamp: null
    name: oneagent
    namespace: ${NAMESPACE}
  stringData:
    apiToken: '${API_TOKEN}'
    paasToken: '${PAAS_TOKEN}'
  type: Opaque
parameters:
- name: NAMESPACE
  displayName: Deployment Namespace
  description: Namespace (or project) used for deployment
  required: true
  value: dynatrace
- name: API_TOKEN
  displayName: API Token
  description: API Token for Dynatrace OneAgent
  required: true
- name: PAAS_TOKEN
  displayName: PaaS Token
  description: PaaS Token for Dynatrace OneAgent
  required: true
