---
kind: Template
apiVersion: v1
metadata:
  name: dynatrace-custom-resource-definition-template
  annotations:
    description: Dynatrace template for the custom SCC used to run Dynatrace monitoring.
objects:
- kind: CustomResourceDefinition
  apiVersion: apiextensions.k8s.io/v1beta1
  metadata:
    name: oneagents.dynatrace.com
    namespace: ${NAMESPACE}
  spec:
    group: dynatrace.com
    names:
      kind: OneAgent
      listKind: OneAgentList
      plural: oneagents
      singular: oneagent
    scope: Namespaced
    version: v1alpha1
parameters:
- name: NAMESPACE
  displayName: Deployment Namespace
  description: Namespace (or project) used for deployment
  required: true
  value: dynatrace
