---
kind: Template
apiVersion: v1
metadata:
  name: dynatrace-serviceaccounts-template
  annotations:
    description: ServiceAccounts template for dynatrace deployment
objects:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: dynatrace-oneagent-operator
    namespace: ${NAMESPACE}
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: dynatrace-oneagent
    namespace: ${NAMESPACE}
parameters:
- name: NAMESPACE
  displayName: Deployment Namespace
  description: Namespace (or project) used for deployment
  required: true
  value: dynatrace
