---

- name: Ensure that the monitoring config directory exists
  file:
    path: "{{ monitoring_config_dir }}"
    state: directory

- name: copy dashboards
  copy:
    src: "{{ dashboard_dir }}"
    dest: "{{ monitoring_config_dir }}/dashboards/"
  when: dashboard_dir is defined

- name: Run the datasources.yml template
  template:
    src: datasources.yml.j2
    dest: "{{ monitoring_config_dir }}/datasources.yml"
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run the dashboard.yml template
  copy:
    src: dashboards.yml
    dest: "{{ monitoring_config_dir }}/dashboards/dashboards.yml"
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run the Grafana Docker container
  docker_container:
    name: grafana
    image: "{{ grafana_image }}:{{ grafana_image_version }}"
    published_ports:
    - "{{ grafana_port }}:3000"
    volumes:
    - "{{ monitoring_config_dir }}/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:Z"
    - "{{ monitoring_config_dir }}/dashboards/:/etc/grafana/provisioning/dashboards/:Z"
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_password }}"
    state: "{{ provision_state }}"
    restart: yes
